import { test, expect } from "@playwright/test";
import { buildUser } from "../../fixtures/data-factory";
import { PostInputSchema, PostSchema } from "./schemas";

/**
 * jsonplaceholder accepts writes and echoes them back with a fresh id but
 * doesn't persist. Fine for contract testing — we're checking the REST
 * surface, not database state.
 *
 * Every response is parsed through a Zod schema before assertions. A drift
 * (server starts returning `userId: "1"` instead of `userId: 1`) fails at
 * `.parse()` with a precise message instead of leaking into a flaky-looking
 * `toMatchObject` failure ten lines later.
 */
test.describe("jsonplaceholder — posts (schema-validated CRUD)", () => {
  test("POST /posts creates a post that round-trips the schema", async ({
    request,
  }) => {
    const user = buildUser();
    const payload = PostInputSchema.parse({
      title:  `Portfolio test — ${user.username}`,
      body:   "Generated by the qa-ai-automation-framework test suite.",
      userId: 1,
    });

    const res = await request.post("/posts", { data: payload });
    expect(res.status()).toBe(201);

    const created = PostSchema.parse(await res.json());
    expect(created).toMatchObject(payload);
    expect(created.id).toBeGreaterThan(0);
  });

  test("PUT /posts/:id replaces a post", async ({ request }) => {
    const payload = PostSchema.parse({
      id:     1,
      title:  "Replaced title",
      body:   "Replaced body",
      userId: 1,
    });

    const res = await request.put("/posts/1", { data: payload });
    expect(res.status()).toBe(200);
    expect(PostSchema.parse(await res.json())).toEqual(payload);
  });

  test("PATCH /posts/:id partially updates a post (untouched fields preserved)", async ({
    request,
  }) => {
    const res = await request.patch("/posts/1", {
      data: { title: "Patched title only" },
    });
    expect(res.status()).toBe(200);

    // Server returns the whole resource on PATCH — schema-validate it before
    // asserting the diff. If the upstream ever switches to returning only the
    // patched fields, this catches it at parse time.
    const after = PostSchema.parse(await res.json());
    expect(after.title).toBe("Patched title only");
    expect(after.body).toBeDefined();
    expect(after.userId).toBeDefined();
  });

  test("DELETE /posts/:id returns 200 with an empty payload", async ({
    request,
  }) => {
    const res = await request.delete("/posts/1");
    expect(res.status()).toBe(200);
    expect(await res.json()).toEqual({});
  });

  test("GET /posts/99999 returns 404 — negative path enforced by schema", async ({
    request,
  }) => {
    const res = await request.get("/posts/99999");
    expect(res.status()).toBe(404);
    // Body should NOT match PostSchema — explicitly assert the negative.
    expect(PostSchema.safeParse(await res.json()).success).toBe(false);
  });
});
